/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        window: {
          'base': '#171717',
          'border': '#404040',
          'border-focus': '#6b7280',
          'header': '#1f1f1f',
          'header-focus': '#262626',
          'header-border': '#333333',
          'header-border-focus': '#404040',
          'content': '#171717',
          'text': '#d1d5db',
          'icon-color': '#9ca3af',
          'button-hover': '#404040',
          'button-close-hover': '#dc2626',
          'resize-handle': '#6b7280',
          'resize-handle-hover': '#d1d5db',
        },
        dock: {
          'base': '#171717',
          'border': '#404040',
          'item': '#262626',
          'item-hover': '#404040',
          'item-active': '#4b5563',
          'text': '#d1d5db',
          'text-active': '#ffffff',
          'text-dim': '#6b7280',
          'icon-dim': '#9ca3af',
          'badge': '#dc2626',
          'badge-text': '#ffffff',
          'separator': '#525252',
          'empty-text': '#525252',
        },
        ui: {
          'input-bg': '#262626',
          'input-border': '#525252',
          'input-text': '#e5e7eb',
          'input-placeholder': '#6b7280',
          'button-primary-bg': '#2563eb',
          'button-primary-hover': '#3b82f6',
          'button-primary-text': '#ffffff',
          'button-disabled-bg': '#262626',
          'button-disabled-text': '#737373',
          'tab-active-border': '#06b6d4',
          'tab-active-bg': '#262626',
          'tab-active-text': '#ffffff',
          'tab-inactive-text': '#6b7280',
          'tab-hover-bg': '#262626',
          'sidebar': '#171717',
        },
        log: {
          'combat': '#f87171',
          'narrative': '#c084fc',
          'speech': '#fde047',
          'error': '#dc2626',
          'command': '#0891b2',
          'success': '#4ade80',
          'info': '#9ca3af',
          'warning': '#fbbf24',
          'timestamp': '#ffffff4d',
        }
      }
    }
  },
  plugins: [],
}
